type: "cub"
save_path: "ckpt/articulated-cub"

train_base_folder: "./dataset/mbs-shapepart"
test_base_folder: "../dataset/mbs-sapien"
val_base_folder: "./dataset/mbs-shapepart"

epochs: 50
batch_size: 16

lr: 1.0e-3
lr_decay: 0.7
lr_clip: 1.0e-5

bn_momentum: 0.9
bn_decay: 0.5
weight_decay: 0.0
decay_step: 300000

W_REC: 1.00
W_std: 0.05
W_SPS: 0.10
W_EXT: 0.01
W_KLD: 6.0e-6
W_CST: 0.00